### ISSUE TITLE
ecp-suite test failed

### ISSUE THREAD

**Issue by lhuang04** [hannestschofenig/mbedtls#103]
The `ecp-suite` test failed for me in `tls13-prototype` branch. It works in `development` branch.
It look like  `mbedtls_ecp_tls_read_point`  expects [the length of input is bigger than 2](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ecp.c#L1014-L1016). However, the test data in `test_suite_ecp.data` is not as [expected](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/tests/suites/test_suite_ecp.data#L151-L161).

Here is how I repo it:
```
mkdir build; cd build
CFLAGS="-std=c99"  cmake ..
make
make  test
```

**Comment by hannestschofenig** [comment]
Working on it ... #116 
The ecp-suite now passes but there still problems with those two:
         67 - pkwrite-suite (Failed)
         84 - x509write-suite (Failed)

**Comment by hannestschofenig** [comment]
Fixed with this PR: https://github.com/hannestschofenig/mbedtls/pull/160
