### ISSUE TITLE
Fail if pre_shared_key extension is not the last extension in ClientHello

### ISSUE THREAD

**Issue by gbryant-arm** [hannestschofenig/mbedtls#113]
In chapter 4.2 of the RFC, a verse says:
>    When multiple extensions of different types are present, the
   extensions MAY appear in any order, with the exception of
   "pre_shared_key" (Section 4.2.11) which MUST be the last extension in
   the ClientHello (but can appear anywhere in the ServerHello
   extensions block).
   
   That doesn't seem to be enforced in the proto

**Comment by hanno-becker** [comment]
I agree, good spot. This also has to be fixed in order to get the PSK binder calculations right. I'm working on it.
