### ISSUE TITLE
Chosen key exchange mode shouldn't be part of SSL session structure

### ISSUE THREAD

**Issue by hanno-becker** [hannestschofenig/mbedtls#14]
__Background:__ Fundamentally, there are three different categories of data processed during a TLS connection: 
* Handshake-local data, which is only relevant for the duration of the handshake.
* Context-local data, which is only relevant for the duration of a specific connection.
* Session-local data, which is relevant for the entire duration of a session, across resumption.

Handshake-local data resides in `mbedtls_ssl_handshake_params`, context local data resides in `mbedtls_ssl_context`, and session-local data resides in `mbedtls_ssl_session`.

It's not always clear to decide where some piece of information belongs, but generally we should strive to find the place of shortest lifetime in the interest of saving RAM as well as conceptual clarity.

For pre-TLS 1.3, the SSL session contains the identifier for the ciphersuite, which for those versions encompasses both key exchange and bulk encryption mechanism. In TLS 1.3, those pieces of information are treated separately, and we need to decide where we put each of them.

__Issue:__ It seems that the key exchange mode `key_exchange_modes, key_exchange` is actually only handshake-local, because it's neither needed after the handshake nor for session resumption, as far as I see. At the moment, however, the chosen key exchange method is stored in `mbedtls_ssl_session`.

**Comment by yuhaoth** [comment]
merged .
