### ISSUE TITLE
Fix namespacing of TLS 1.3 HKDF code

### ISSUE THREAD

**Issue by hanno-becker** [hannestschofenig/mbedtls#16]
The TLS 1.3 HKDF code needs to move to the Mbed TLS namespace.

**Comment by hannestschofenig** [comment]
Guilhem, I believe you have fixed this issue with https://github.com/hannestschofenig/mbedtls/pull/36

**Comment by gbryant-arm** [comment]
I haven't fixed it, it seems to be in the namespace already

**Comment by hanno-becker** [comment]
Fixed while upstreaming the TLS 1.3 HKDF code, see https://github.com/ARMmbed/mbedtls/pull/3568
