### ISSUE TITLE
Out-of-the-box Makefile-based build fails

### ISSUE THREAD

**Issue by hanno-becker** [hannestschofenig/mbedtls#165]
A plain `make` fails with an undefined reference error from the `mini_client` example program, missing symbol definitions for `mbedtls_ssl_{client,server}_handshake_step()`. This doesn't occur for me when building with cmake.

**Comment by hanno-becker** [comment]
This applies to other example programs, too. I am very puzzled, but for some reason the TLS 1.3 specific source files aren't part of `library/Makefile` -- have we never built the library with plain `make`?

**Comment by hannestschofenig** [comment]
No, we have been using Visual Studio and cmake but not make. Hence, we need to update the Makefiles as well...
