### ISSUE TITLE
Re-enable SSL test suite

### ISSUE THREAD

**Issue by hanno-becker** [hannestschofenig/mbedtls#18]
The SSL test suite is currently disabled when TLS 1.3 is enabled in the config.

**Comment by hannestschofenig** [comment]
The tests work again based on various PRs (including https://github.com/hannestschofenig/mbedtls/pull/163 and https://github.com/hannestschofenig/mbedtls/pull/160)

**Comment by hanno-becker** [comment]
@hannestschofenig I don't think those PRs address the SSL test suite.

**Comment by yuhaoth** [comment]
relative patch has been merged
