### ISSUE TITLE
ssl_client2 resumption fails

### ISSUE THREAD

**Issue by zhihan** [hannestschofenig/mbedtls#249]
I use the following command to connect to a local server. The first connection succeeded but the second connection (resumption) failed with a fatal alert.

I tested using both BoringSSL server and OpenSSL server. From the debug log, it looks the error is generated from the PSK binder verification. The failure are from the following points:
1. OpenSSL: [here](https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/ssl/statem/extensions.c#L1594)
2. BoringSSL: [here](https://cs.android.com/android/platform/superproject/+/master:external/boringssl/src/ssl/tls13_enc.cc;l=503;drc=17486117acfddecea663c62f1aed75589a632ce5)

[debug.log](https://github.com/hannestschofenig/mbedtls/files/6416470/debug.log)

**Comment by zhihan** [comment]
Verified that it was working at a05e08083c580d4f18b3d9a50443883cb39a3289 with `force_ciphersuite=TLS_AES_128_GCM_SHA256`. Further bisect found the issue has started since https://github.com/hannestschofenig/mbedtls/commit/97cafd713f9295c526ea92f39b2fdf7ed102bb4d

**Comment by zhihan** [comment]
It looks the function `mbedtls_ssl_generate_resumption_master_secret` is using `handshake_secret` instead of `master_secret`. Changing this at https://github.com/hannestschofenig/mbedtls/commit/97cafd713f9295c526ea92f39b2fdf7ed102bb4d fixes the problem. But this code has been fixed in https://github.com/hannestschofenig/mbedtls/commit/f5cbabedd40bcd7c2c7e3cf5ba5c6f8aadb0333b#diff-b67c0adff0a54f6cc5e2401f775e88ab9a2946c4e2e1c5c9cf07f3222a5f2eac. But somehow the change was lost in later revisions.

**Comment by zhihan** [comment]
Looks like it is recently broken by https://github.com/hannestschofenig/mbedtls/commit/719928c24a6e5d73c56c58513bd6beafe6072e22

**Comment by hanno-becker** [comment]
Thank you @zhihan for investigating this. I'll take a look.

**Comment by hanno-becker** [comment]
@zhihan I believe to have fixed this -- could you check against current `tls13-prototype`?

**Comment by zhihan** [comment]
Yes it is fixed. Thanks, Hanno.
