### ISSUE TITLE
ssl_client2 error when early_data is rejected

### ISSUE THREAD

**Issue by zhihan** [hannestschofenig/mbedtls#255]
### Description
- Type: Bug
- Priority:  Major

---------------------------------------------------------------
## Bug

**OS**  
MacOS

When server rejects the early data, it seems the client fails to continue talking to the server with 1-RTT. I observe different failures with different servers. With boringssl server, when early_data is not supported, the server sends hello_retry and then the client hangs. The logs show the server is waiting for second client_hello but the client is waiting for server_hello. 
With OpenSSL server, the server sends sever_hello indicating that early_data was rejected, the client continue to send application data but the server is not able decrypt it. With `mbedtls` server2, it fails with an unknown error.

# Reproduce

## boringssl 
Start the boringssl server using

```
./bssl server -accept 1234 -loop -debug
```

Start the client using

```
./ssl_client2 server_name=localhost server_port=1234 auth_mode=none reconnect=1 force_ciphersuite=TLS_AES_128_GCM_SHA256  early_data=1 debug_level=3
```

* [client_boringssl.log](https://github.com/hannestschofenig/mbedtls/files/6427776/client_boringssl.log)
* [boringssl_server.log](https://github.com/hannestschofenig/mbedtls/files/6427777/boringssl_server.log)

## OpenSSL
Start the OpenSSL server using

```
/usr/local/opt/openssl/bin/openssl s_server -state -port 1234 -cert server5.crt -key server5.key -debug
```

Then start the client using

```
./ssl_client2 server_name=localhost server_port=1234 auth_mode=none reconnect=1 force_ciphersuite=TLS_AES_128_GCM_SHA256  early_data=1 debug_level=3
```

* [client_openssl.log](https://github.com/hannestschofenig/mbedtls/files/6427752/client_openssl.log)
* [openssl_server.log](https://github.com/hannestschofenig/mbedtls/files/6427750/openssl_server.log)

## mbedtls server

Start the server using

```
./ssl_server2 server_port=1234 debug_level=3
```

Start the client using

```
./ssl_client2 server_name=localhost server_port=1234 auth_mode=none reconnect=1 force_ciphersuite=TLS_AES_128_GCM_SHA256  early_data=1 debug_level=3
```

* [client_mbedtls.log](https://github.com/hannestschofenig/mbedtls/files/6427965/client_mbedtls.log)
* [mbedtls_server.log](https://github.com/hannestschofenig/mbedtls/files/6427964/mbedtls_server.log)

**Comment by hanno-becker** [comment]
@zhihan This can be closed now, right?

**Comment by zhihan** [comment]
The issue with openssl is fixed. The other two problems (boringssl and mbedtls) still exist.

**Comment by zhihan** [comment]
Did some more debugging, it seems to me that the bug in bosingssl is because we did not set the msgtype correctly. After receiving HRR, the client sends the second client hello with type set to 23 (Application data). `boringssl` treat it as early data and discard it. Then the server hangs waiting for second client hello, while client hangs waiting for server hello.

The first byte below should be 0x16 instead of 0x17.
```
ssl_msg.c:3135: |4| dumping 'output record sent to network' (23 bytes)
ssl_msg.c:3135: |4| 0000:  17 03 03 00 12 58 96 c6 be 82 2c f2 1f 69 a0 76  .....X....,..i.v
ssl_msg.c:3135: |4| 0010:  75 94 df ef 94 39 3e                             u....9>
```

**Comment by hanno-becker** [comment]
@zhihan This sounds like we're setting the 0-RTT keys too early on... checking.

**Comment by hanno-becker** [comment]
Hmm, this is actually a tricky case: If the client uses 0-RTT but the server sends an HRR, we need to _rewind_ the key schedule to 'no encryption', which isn't happening anywhere else in TLS. I need to think about how to best do this...

**Comment by hanno-becker** [comment]
I think we should aim to implement this in an almost stateless fashion: If the client receives a HRR, we reset the entire handshake but remember (a) the transcript state, (b) the constraints posed by the HRR. The generic `ClientHello` writing routine should take those factors into account if present.

**Comment by zhihan** [comment]
In the openssl case, the server simply rejected the early data without sending HRR. That is why we did not observe this behavior.

**Comment by zhihan** [comment]
> I think we should aim to implement this in an almost stateless fashion: If the client receives a HRR, we reset the entire handshake but remember (a) the transcript state, (b) the constraints posed by the HRR. The generic `ClientHello` writing routine should take those factors into account if present.

I might be wrong, but it looks to me (a) is already implemented [here](https://github.com/hannestschofenig/mbedtls/blob/38a3de888bbbca7cd7394e81bf7617ac716327fa/library/ssl_tls13_client.c#L3871). I don't see where we reset the handshake, though. Adding a line 
``` 
ssl->transform_out = NULL;
```
to `ssl_hrr_postprocess` seems to fix it if `MBEDTLS_SSL_USE_MPS ` is disabled. The bug still exists for `MBEDTLS_SSL_USE_MPS`, I don't think mps uses the `transform_out` function.

**Comment by hanno-becker** [comment]
@zhihan Could you check whether this issue is still present after #275 ?

**Comment by zhihan** [comment]
Verified that this no longer happens now. Thanks @hanno-arm for fixing it.
