### ISSUE TITLE
Unable to connect to OpenSSL TLS1.3 Server

### ISSUE THREAD

**Issue by embien** [hannestschofenig/mbedtls#28]
Hi,

  We are trying to connect mbed TLS 1.3 client(right now in Win32) to an OpenSSL server, but always it ends up as ECP - The signature is not valid error.

```
ssl_tls13_messaging.c:2706: |5| <= read record
ssl_tls13_generic.c:2076: |3| Certificate Verify: Signature algorithm ( 0503 )
ssl_tls13_generic.c:2115: |1| mbedtls_pk_verify() returned -19968 (-0x4e00)
ssl_tls13_generic.c:1986: |2| <= parse certificate verify
ssl_tls13_client.c:4185: |1| ssl_read_certificate_verify_process() returned -19968 (-0x4e00)
ssl_tls.c:6082: |2| <= handshake
 failed
  ! mbedtls_ssl_handshake returned -0x4e00
```

We could make the same certificates work with mbed TLS 1.3 server + client and also with OpenSSL TLS1.3 server + client. It is not working when either of them is attempted with other.

  What are we missing?

**Comment by hannestschofenig** [comment]
We introduced a bug in the signature algorithm handling when refactoring the code. The bug fix is here: https://github.com/hannestschofenig/mbedtls/pull/32

It is also worthwhile mentioning that the compability mode needs to be enabled in order for the exchange to work with OpenSSL. I will double-check this...

**Comment by embien** [comment]
Hi,

  Thanks a lot for your response. Unfortunatly still we are facing the same issue. Please find the logs attached herewith.

  And yes, compatibility mode is needed.

[
[log.txt](https://github.com/hannestschofenig/mbedtls/files/5249769/log.txt)
](url)

**Comment by hannestschofenig** [comment]
I fixed the issue and you can find the working code in https://github.com/hannestschofenig/mbedtls/pull/32
(branch signature-algorithms)

I have tested it against OpenSSL with the following configuration setting: 

> openssl s_server -cert certs/server.crt -key certs/server.key -accept 4430 -debug -tls1_3

> ./ssl_client2  debug_level=5 force_version=tls1_3 server_name=localhost server_addr=IP_ADDRESS key_exchange_modes=ecdhe_ecdsa auth_mode=none force_ciphersuite=TLS_AES_128_GCM_SHA256 server_port=4430 named_groups=secp256r1 key_share_named_groups=secp256r1 sig_algs=ecdsa_secp256r1_sha256 tickets=0

(Note: you could configure the certificates appropriately so that verification works as well and the auth_mode=none isn't required)

**Comment by embien** [comment]
Thanks a lot Hannes!  It is working with TLS_AES_128_GCM_SHA256 .

But still TLS_AES_256_GCM_SHA384 is failing. Is it possible for you to have a quick look into it?

**Comment by hannestschofenig** [comment]
Thanks for checking. I fixed the bug in https://github.com/hannestschofenig/mbedtls/pull/32/commits/3b2660978cf22bb82f1e37b75aa43573efb8a27e

Note that I added some more code to the branch to allow more flexible configuration for the ssl_client2.c and ssl_server2.c example programs, which you are probably not interested in.

I tested the code with the following configuration setting: 

> openssl s_server -cert certs384/server384.crt -key certs384/server384.key -accept 4430 -debug -tls1_3 -ciphersuites TLS_AES_256_GCM_SHA384

> ./ssl_client2 debug_level=5 force_version=tls1_3 server_name=localhost server_addr=IP_ADDRESS key_exchange_modes=ecdhe_ecdsa auth_mode=none force_ciphersuite=TLS_AES_256_GCM_SHA384 server_port=4430 named_groups=secp384r1 key_share_named_groups=secp384r1 sig_algs=ecdsa_secp384r1_sha384 tickets=0

Note that I created new certificates that use SHA384 and I also tweaked the parameters on the client side to force the selection of this signature algorithm and the related curves. 

I hope this works for you

**Comment by embien** [comment]
Hi!

Thanks a lot and it works. We are able to pull in HTTPS data from Apache server with the same.

But when we try to run MQTT stack on top if it, we are getting error -0x7180 (SSL - Verification of the message MAC failed). 
What could be the reason?

**Comment by hannestschofenig** [comment]
TLS shouldn't actually care what protocol you run on top of it. So, MQTT and HTTP should behave the same when secured by TLS. 

Do you have a log file to see whether the TLS configuration changed in some way? At what point in the exchange does the MAC failure occur? After the handshake was completed successfully?

**Comment by hannestschofenig** [comment]
Maybe we should do a quick call to look at this together. Drop me an email at Hannes.Tschofenig@arm.com, if you have time.

**Comment by hannestschofenig** [comment]
After discussions we found out that the application data traffic secrets were computed with the full transcript as input while OpenSSL uses (correctly) only the transcript up to the server.finished message. This bug has been corrected with https://github.com/hannestschofenig/mbedtls/pull/32

**Comment by embien** [comment]
Dear Hannes,

    Greetings!

     We have succesfully ported the stack to STM32 and we are able to do both MQTT and HTTPS communication. One point we observed it is that there seems to be a memory leak after we make a connection and close it.

     The function mbedtls_set_traffic_key sets up ciphers using mbedtls_cipher_setkey( &transform->cipher_ctx_enc, ...) and mbedtls_cipher_setkey( &transform->cipher_ctx_dec,...) calls. The memory allocated inside mbedtls_cipher_setup function is not cleared using mbedtls_cipher_free. We have called all the free functions at the end of the connection (mbedtls_ssl_close_notify, mbedtls_ssl_del_client_ticket and mbedtls_free_resource).

     Are we missing some thing?

     Apart of these there is one more leak involving some 8 bytes, which we are yet to identify.

     BTW still we are using the code based on signature_algorithms branch. I see that you have removed it. What is the code base you recommend us to move to?

Regards,
Saravana Pandian.S.A.
