### ISSUE TITLE
Pre-Shared Key Exchange Modes extension should be sent in Client Hello when client supports psk_dhe_ke

### ISSUE THREAD

**Issue by lhuang04** [hannestschofenig/mbedtls#397]
### Summary
[A recent commit](https://github.com/hannestschofenig/mbedtls/commit/6828b87f8ce7042c453bff841c46c5e38ea33f17) added the logic to send key exchange mode ext only when offering a PSK. As a result, the client may not add `Pre-Shared Key Exchange Modes` extension in the very initial `Client Hello`. And our server will not send New Session Ticket(NST) to client if there is no `Pre-Shared Key Exchange Modes` extension in the client hello. In `psk_dhe_ke` mode, client can only offer PSK if it has received NST from previous session.

Looking at the [RFC](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.9), it seems correct that server may not sent NST to client when there is no `Pre-Shared Key Exchange Modes` extension in the client hello.
```
   In order to use PSKs, clients MUST also send a
   "psk_key_exchange_modes" extension.  The semantics of this extension
   are that the client only supports the use of PSKs with these modes,
   which restricts both the use of PSKs offered in this ClientHello and
   those which the server might supply via NewSessionTicket.
```

Another issue with [the commit](https://github.com/hannestschofenig/mbedtls/commit/6828b87f8ce7042c453bff841c46c5e38ea33f17) is that the `*out_len` should be set to 0 when the function [returns early](https://github.com/hannestschofenig/mbedtls/commit/6828b87f8ce7042c453bff841c46c5e38ea33f17#diff-ef6f5faac0e0b98311d2daf2dfad61a856336e27a7a22ee248b88e72013781efR723-R726).

```
    if( mbedtls_ssl_get_psk_to_offer( ssl, &psk, &psk_len,
                                      &psk_identity, &psk_identity_len ) != 0 )
    {
        MBEDTLS_SSL_DEBUG_MSG( 3, ( "skip psk_key_exchange_modes extension" ) );
        return( 0 );
    }
```

Should be
```
    if( mbedtls_ssl_get_psk_to_offer( ssl, &psk, &psk_len,
                                      &psk_identity, &psk_identity_len ) != 0 )
    {
        MBEDTLS_SSL_DEBUG_MSG( 3, ( "skip psk_key_exchange_modes extension" ) );
        *out_len = 0;
        return( 0 );
    }
```

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

**Comment by lhuang04** [comment]
cc @ronald-cron-arm

**Comment by ronald-cron-arm** [comment]
@lhuang04 you are right, sorry for the inconvenience. I forgot about the ticket enablement part of the pre shared key exchange modes extension. I will revert the commit.
