### ISSUE TITLE
Errors if `MBEDTLS_SSL_CLI_C` is disabled

### ISSUE THREAD

**Issue by gbryant-arm** [hannestschofenig/mbedtls#47]
Errors show up if `MBEDTLS_SSL_CLI_C` is not set:

* ticket handling: `mbedtls_ssl_ticket_flags` structure is defined for MBEDTLS_SSL_CLI_C only, although it's used by the server too
* some variables are not used
* several server-side functions should not be compiled, e.g. `mbedtls_ssl_parse_new_session_ticket()`, `mbedtls_ssl_conf_client_ticket()`, etc. See  `ssl_finished_in_postprocess()`, which is properly guarded

**Comment by hannestschofenig** [comment]
I have created two PRs that fixe error related to client- and server-only builds in PR #62 and PR #63

**Comment by gbryant-arm** [comment]
Fixed in #62 and #63
