### ISSUE TITLE
TLS 1.3 Middlebox compatibility mode doesn't compile

### ISSUE THREAD

**Issue by hanno-becker** [hannestschofenig/mbedtls#9]
Enabling `MBEDTLS_COMPATIBILItY_MODE` (or, after https://github.com/hannestschofenig/mbedtls/pull/8, `MBEDTLS_SSL_TLS13_COMPATIBILITY_MODE`) doesn't compile.

**Comment by hannestschofenig** [comment]
True. I haven't refactored that code. I can take care of it.

**Comment by hannestschofenig** [comment]
This issue is being fixed with https://github.com/hannestschofenig/mbedtls/pull/32
